image:
  name: hashicorp/packer:latest
  entrypoint: [""]

variables:
  AWS_ACCESS_KEY_ID: AKIAIERO26RY3JEQ6ICA

stages:
  - build-eks-ami

build-eks-ami:
  stage: build-eks-ami
  script:
    - apk update && apk add make py-pip
    - pip install awscli >/dev/null
    - make all
  only:
    - master
