image:
  name: hashicorp/packer:latest
  entrypoint: [""]

variables:
  AWS_ACCESS_KEY_ID: AKIAIERO26RY3JEQ6ICA

stages:
  - build-eks-ami

build-eks-ami:
  stage: build-eks-ami
  script:
    - make all
  only:
    - master
